version: '3.8'

services:
  telegram-bot:
    image: node:18-alpine
    working_dir: /app
    command: ["sh", "-c", "cp package*.json bot.js test-proxy.js /app/ 2>/dev/null || true && npm install --only=production && node bot.js"]
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - bot-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production

networks:
  bot-network:
    driver: overlay
