version: '3.8'

services:
  telegram-bot:
    image: node:18-alpine
    working_dir: /app
    command: >
      sh -c "
        apk add --no-cache git &&
        git clone --branch main --depth 1 https://github.com/mrmaggie21/MRBOOT.git /tmp/repo &&
        cp -r /tmp/repo/* /app/ &&
        cp -r /tmp/repo/.[!.]* /app/ 2>/dev/null || true &&
        rm -rf /tmp/repo &&
        npm install --only=production &&
        node bot.js
      "
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    networks:
      - bot-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_TOKEN=${API_TOKEN}
      - API_BASE_URL=${API_BASE_URL:-https://completa.workbuscas.com/api}
      - USE_PROXY=${USE_PROXY:-true}
      - WEBSHARE_API_KEY=${WEBSHARE_API_KEY}
      - WEBSHARE_API_URL=${WEBSHARE_API_URL:-https://proxy.webshare.io/api/v2/proxy/list}

networks:
  bot-network:
    driver: overlay
