version: '3.8'

services:
  telegram-bot:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "if [ ! -d /app/node_modules ]; then npm install --only=production; fi && node bot.js"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production

networks:
  bot-network:
    driver: overlay
