version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        cache-from: []
    container_name: telegram-cpf-bot
    restart: unless-stopped
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production
      - DOCKER_BUILDKIT=0

networks:
  bot-network:
    driver: bridge

